//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeOffice.Client.ExchangeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestConnection", ReplyAction="http://tempuri.org/IService1/TestConnectionResponse")]
        string TestConnection(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestConnection", ReplyAction="http://tempuri.org/IService1/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        decimal GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        string TestDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        System.Threading.Tasks.Task<string> TestDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PerformExchange", ReplyAction="http://tempuri.org/IService1/PerformExchangeResponse")]
        string PerformExchange(int userId, string fromCurrency, string toCurrency, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PerformExchange", ReplyAction="http://tempuri.org/IService1/PerformExchangeResponse")]
        System.Threading.Tasks.Task<string> PerformExchangeAsync(int userId, string fromCurrency, string toCurrency, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionHistory", ReplyAction="http://tempuri.org/IService1/GetTransactionHistoryResponse")]
        string[] GetTransactionHistory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionHistory", ReplyAction="http://tempuri.org/IService1/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<string[]> GetTransactionHistoryAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ExchangeOffice.Client.ExchangeService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ExchangeOffice.Client.ExchangeService.IService1>, ExchangeOffice.Client.ExchangeService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection(string userName) {
            return base.Channel.TestConnection(userName);
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync(string userName) {
            return base.Channel.TestConnectionAsync(userName);
        }
        
        public decimal GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public string TestDatabaseConnection() {
            return base.Channel.TestDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestDatabaseConnectionAsync() {
            return base.Channel.TestDatabaseConnectionAsync();
        }
        
        public string PerformExchange(int userId, string fromCurrency, string toCurrency, decimal amount) {
            return base.Channel.PerformExchange(userId, fromCurrency, toCurrency, amount);
        }
        
        public System.Threading.Tasks.Task<string> PerformExchangeAsync(int userId, string fromCurrency, string toCurrency, decimal amount) {
            return base.Channel.PerformExchangeAsync(userId, fromCurrency, toCurrency, amount);
        }
        
        public string[] GetTransactionHistory(int userId) {
            return base.Channel.GetTransactionHistory(userId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTransactionHistoryAsync(int userId) {
            return base.Channel.GetTransactionHistoryAsync(userId);
        }
    }
}
